const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE:'CHANGE_LANGUAGE',



    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',


    //admin
    FETCH_GENDER_START:'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS:'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED:'FETCH_GENDER_FAILED',


    FETCH_POSITION_START:'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS:'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED:'FETCH_POSITION_FAILED',

    FETCH_ROLE_START:'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS:'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED:'FETCH_ROLE_FAILED',

    CREATE_USER_SUCCESS:'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED:'CREATE_USER_FAILED',

    DELETE_USER_SUCCESS:'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED:'DELETE_USER_FAILED',

    EDIT_USER_SUCCESS:'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED:'EDIT_USER_FAILED',

    FETCH_ALL_USERS_SUCCESS:'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED:'FETCH_ALL_USERS_FAILED',

    FETCH_TOP_DOCTORS_SUCCESS:'FETCH_TOP_DOCTORS_SUCCESS',
    FETCH_TOP_DOCTORS_FAILED:'FETCH_TOP_DOCTORS_FAILED',

    FETCH_ALL_DOCTORS_SUCCESS:'FETCH_ALL_DOCTORS_SUCCESS',
    FETCH_ALL_DOCTORS_FAILED:'FETCH_ALL_DOCTORS_FAILED',

    FETCH_SAVE_INFOR_DOCTORS_SUCCESS:'FETCH_SAVE_INFOR_DOCTORS_SUCCESS',
    FETCH_SAVE_INFOR_DOCTORS_FAILED:'FETCH_SAVE_INFOR_DOCTORS_FAILED',

    FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS:'FETCH_ALLCODE_SCHEDULE_TIME_SUCCESS',
    FETCH_ALLCODE_SCHEDULE_TIME_FAILED:'FETCH_ALLCODE_SCHEDULE_TIME_FAILED',

    FETCH_REQUIRED_DOCTOR_INFOR_START:'FETCH_REQUIRED_DOCTOR_INFOR_START',
    FETCH_ALL_REQUIRED_DOCTOR_INFOR_SUCCESS:'FETCH_ALL_REQUIRED_DOCTOR_INFOR_SUCCESS',
    FETCH_ALL_REQUIRED_DOCTOR_INFOR_FAILED:'FETCH_ALL_REQUIRED_DOCTOR_INFOR_FAILED',

    FETCH_SAVE_INFOR_CLINICS_SUCCESS:'FETCH_SAVE_INFOR_CLINICS_SUCCESS',
    FETCH_SAVE_INFOR_CLINICS_FAILED:'FETCH_SAVE_INFOR_CLINICS_FAILED',

    DELETE_CLINIC_SUCCESS:'DELETE_CLINIC_SUCCESS',
    DELETE_CLINIC_FAILED:'DELETE_CLINIC_FAILED'
})

export default actionTypes;